### ISSUE TITLE
Add voting feature

### ISSUE THREAD

**Issue by ymstnt** [tchfoo/moe#7]
The bot definitely needs a voting feature, sometimes it could come handy.

### Creating a vote
- Once again, Modals could be used, as they are the most user-friendly for this purpose, but they have that annoying limitation of max. 5 components (so one for the vote prompt and 4 for the choices).
- The second choice would be to use commands only. That way theoretically we could have as many options as the command allows parameters or more if we implement it that way. The main problem with this is that it's not really user-friendly. Having to write a very long one-line command is hard to do and see. Users could get very easily confused.
- The third option would be to use kind of both. Maybe set the voting prompt in the command itself, and call a Modal for the choices, then we could have 5 choices, and in my opinion, that is more than enough. The problem with this, is again, user-friendliness. What if the prompt is a long one, then we have the same problem, as before.
- The best way would be to have 2 modals, one asks for the prompt and the other for the choices. However, according to the Discord Developer documentation and the Discord.NET documentation, modals cannot be responded with modals, so this poses another challenge.

In any case, the **voting prompt** should be a `TextInputStyle.Paragraph` (in case of a modal) with the max characters set to 1000. The choices should be normal text inputs. They are meant to be short sentences max.

The command should have an optional channel argument, which specifies the channel to send the vote in.
The command should also have a time argument, which specifies how much the vote should run for (in minutes). Whether to have this optional or not is debatable. In my opinion, this should be mandatory, as votes should be closed automatically after a while, to prevent spam and performance issues. I don't know what would be a reasonable max and minimum time, though.

The vote could be restricted to Moderator modrank (to prevent spammy votes), or not, this is debatable.

### Vote progression

This is where it gets complicated.
After the vote is created, an embed is sent with the prompt and selections. Buttons under the embed should be used for selection the options. For the initial implementation, you can only vote on one option at a time, so clicking multiple buttons will result in choosing a different option. (a user can't vote on multiple things at once) This could be changed later, if necessary.

The embed could be edited to track the voting results with progress bars while the vote is going on, but this might lead to rate limits, so this is not necessary.

However, now the complicated part.
Because the voting happens on Discord, and might happen in a channel where chatting takes place (busy channel), the vote might quickly get lost. I propose that we make use of Discord's Thread feature, and after the vote is created and sent, the bot creates a public thread of the vote. That way, the users' client will show a thread icon in the top, allowing them to always take a look at the vote while it is running. This makes more sense if the embed is updated for progress, but it also makes sense without that feature: users could find running votes easily. After the vote is ended, the thread could be closed and archived.
Further testing is required about how threads work, if they conflict with buttons etc.

### Ending the vote

As I mentioned before, votes would auto end after the set time is elapsed. When the vote ends, the thread closes and archives, and the result gets sent in the same channel where the vote was started.
However, users should be able to manually close the votes too. `/vote close` command could be used to close a vote. Only the user who started the vote can close it, but there should be an override for Administrator and above, who can close the vote too.

### Multiple votes

The bot could support multiple votes running concurrently. This can only be done if each vote gets supplied an identifier, which can be referenced to in the `/vote close` command. This is also useful for the automatic close feature.

There could be a limit on concurrent votes for performance reasons. 5 or 10 concurrent votes is an acceptable number and probably is good enough.

**Comment by gutyina70** [comment]
> The best way would be to have 2 modals, one asks for the prompt and the other for the choices. However, according to the Discord Developer documentation and the Discord.NET documentation, modals cannot be responded with modals, so this poses another challenge.

We could overcome this by sending a message with a button that opens a modal. And with this method, it's easier to make unlimited choices.

My full idea of vote creation is: The user runs `/vote create`. A modal opens with **a title** and **4 choices**. In the background an ephemeral message is sent with buttons **Add choices** and **Create vote**. Clicking on Add choices will open a modal with **5 choice** inputs, and it can be repeated many times. And create vote button is self-explanatory.

**Comment by YMSTNT** [comment]
> My full idea of vote creation is: The user runs `/vote create`. A modal opens with **a title** and **4 choices**. In the background an ephemeral message is sent with buttons **Add choices** and **Create vote**.

That's a good idea, but how many buttons can be on a single message? I don't really like the infinite choices thing, because
1) It's useless. No one needs like more than 10 choices. (Even 10 is a bit much imo)
2) There is probably a limit on how many buttons can be on a message. And from a user-friendly standpoint, there shouldn't be too much.

**Comment by gutyina70** [comment]
Max is 25 buttons. Same limit with select menus if we want to use that instead of buttons. Since I don't know how many choices do you want (4 choices are not enough but 5 are too many?) so you decide which vote creation should we use.

**Comment by YMSTNT** [comment]
Minimum should be 2.

The first modal will feature a prompt + 4 choices.

The second will feature an additional 5 choices, but that's entirely optional, of course.

Above 10 choices is overkill, imo. We could increase the limit later if needed, but for now let's keep the max choices **9**. This is because the two modals add up that many choices. (I don't want another small modal just for the 10th choice).

**Comment by gutyina70** [comment]
What parameters should `/vote create` have?
Since we want to utilize threads but also allow the user to specify a channel where the vote should be in, we could do one of the following:

1. Have an optional parameter called **channel**. The bot will send the vote there if specified, otherwise it will send it in a newly created thread.
2. Have an optional parameter called **channel** and a boolean called **thread** (or use-thread). If thread is true, it will message in a new thread, if false it will message to the channel that defaults to current channel. This may or may not be more confusing than 1.
3. Have an optional parameter called **channel**. The bot will always send a message to a new thread and to the channel that defaults to current channel.

For time limit parameter, it could be minimum 10 seconds, maximum 1 week and if not specified, it can default to 5 minutes. I don't think performance will be a big issue, especially if we will limit the number of concurrent votes to something like 10-20.

**Comment by YMSTNT** [comment]
> 3. Have an optional parameter called **channel**. The bot will send a message to both a new thread and to the channel that defaults to current channel.

Since the threads are used to keep track of the currently running votes, their use is mandatory. So, go with the 3rd option, an optional channel parameter. However, creating the thread is mandatory, so the channel parameter should set the channel where the thread and the vote is created.

> For time limit parameter, it could be minimum 10 seconds, maximum 1 week and if not specified, it can default to 5 minutes. I don't think performance will be an issue, especially if we will limit the number of concurrent votes to something like 10-20 per guild.
Sure, fine by me.

**Comment by gutyina70** [comment]
The thread name could be a truncated version of the question that matches Discord's style with a prefix. Thread names can be as long as 100 characters. For example the question `Do you like the new voting feature?` would have a thread called `vote-do-you-like-the-new-voting-feature`.

You mentioned `/vote close [vote id]` needs an identifier when multiple votes are running. The identifier could be the thread itself by using a Channel type parameter that accepts PublicThreads. This would be nice because Discord gives autocompletion for it, however the user can enter non-vote threads too, so it may not be the cleanest solution.

Maybe we should have a `/vote show [vote id]` command that sends the vote with buttons to the current channel and makes sure it's in the thread too. This would be useful when the bot is no longer listening for button clicks due to bot restart or some API failure.

**Comment by YMSTNT** [comment]
> The thread name could be a truncated version of the question that matches Discord's style with a prefix. Thread names can be as long as 100 characters. For example the question `Do you like the new voting feature?` would have a thread called `vote-do-you-like-the-new-voting-feature`.

Could work. However, I'm not sure that it would look good in the thread list menu thingy.

> You mentioned `/vote close [vote id]` needs an identifier when multiple votes are running. The identifier could be the thread itself by using a Channel type parameter that accepts PublicThreads. This would be nice because Discord gives autocompletion for it, however the user can enter non-vote threads too, so it may not be the cleanest solution.

Yeah, it might not be the cleanest, but still, could work.

> Maybe we should have a `/vote show [vote id]` command that sends the vote with buttons to the current channel and makes sure it's in the thread too. This would be useful when the bot is no longer listening for button clicks due to bot restart or some API failure.

So, it basically sends the vote again? How would that work? Would the previous thread get archived or something? That is the only way I see this working. The idea is good tho, definitely should avoid potential failures.

**Comment by gutyina70** [comment]
> So, it basically sends the vote again? How would that work? Would the previous thread get archived or something? That is the only way I see this working. The idea is good tho, definitely should avoid potential failures.

It would only work if no one deletes the thread, since the thread will be used as an identifier (unless you have a better idea). The thread doesn't need to be archived, it should reuse the existing one. The bot would send the vote message again to the thread and current channel.

We should store everything in the database. Including the question, the choices and which choice(es) did the user vote for. This way bot restart won't cause any data loss, and after running `/vote show`, everything should be working.

I don't want to touch the sql after we release this feature, so we should finalize how the vote works or could possibly work in the future. Do we want to support multiple choices? If we do, a parameter should be added to `/vote create` (and to the database) indicating the max choices voters can choose.

**Comment by gutyina70** [comment]
> The thread name could be a truncated version of the question that matches Discord's style with a prefix. Thread names can be as long as 100 characters. For example the question `Do you like the new voting feature?` would have a thread called `vote-do-you-like-the-new-voting-feature`.

Thread names have less restrictions than channels, they allow capital letters and punctuation. What about calling the thread `[Vote] Do you like the new voting feature?`?

**Comment by YMSTNT** [comment]
> Thread names have less restrictions than channels, they allow capital letters and punctuation. What about calling the thread `[Vote] Do you like the new voting feature?`?

That's good, and if it needs to be truncated, we could do for example `[Vote] Do you want to play games this w...`, so basically just truncate the last 3 letters and replace it with '...'. Much more cleaner for the user.

**Comment by gepbird** [comment]
Native discord feature
